Knowledge-Management-Capstone/knowledge-management-core

package.json
close https://github.com/dianrahmaji/knowledge-management-dashboard/issues/3
- as titled
=> KMNCORE-3 Fixed Scripts for Heroku Deployment

.github/pull_request_template.md, index.js, package.json, yarn.lock
close https://github.com/dianrahmaji/knowledge-management-core/issues/5
- as titled
=> KMNCORE-5 Fixed CORS

controllers/userController.js, index.js, middlewares/authMiddleware.js, middlewares/errorMiddleware.js, models/userModel.js, package.json, routes/userRoute.js, utils/generateToken.js, yarn.lock
close https://github.com/dianrahmaji/knowledge-management-core/issues/7
- Added `userModel` `userController` and `userRoute`
- Added `authMiddleware` and `errorMiddleware`
- Added `generateToken` utility
=> KMNCORE-7 Configured User API

package.json
close https://github.com/dianrahmaji/knowledge-management-core/issues/9
- Updated version to `0.1.0`
=> KMNCORE-9 Bumped Version

.github/pull_request_template.md
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/12
- updated github templates
=> KMNCORE-12 Updated Github Templates

controllers/adminController.js, index.js, routes/adminRoute.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/14
- Added `adminController` and `adminRoute`
=> KMNCORE-14 Implement Admin Login

controllers/userController.js, models/userModel.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/11
- Added `approveUser` controller
=> KMNCORE-11 Implemented User Approval

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/15
- Omitted Admin from `getAllUsers` controller
=> KMNCORE-15 Omitted Admin from getAllUsers

controllers/userController.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/19
- added `deleteUser` controller and implemented in `userRoute`
=> KMNCORE-19 Added DeleteUser

controllers/userController.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/22
- Added `updateUser` controller
=> KMNCORE-22 Added Update User Controller

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/24
- Fixied `approveUser` controller
=> KMNCORE-24 FIxed Approve Error

controllers/__test__/adminController.test.js, package.json, vitest.config.js, yarn.lock
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/26
- Setup `vitest`
- Setup `c8`
- Added `adminController.test.js`
=> KMNCORE-26 Setup Unit Test

models/documentModel.js, models/folderModel.js, models/messageModel.js, models/repositoryModel.js, models/teamModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/32
- Added Database Models
- Added Database Relations (as designed in the image below)
=> KMNCORE-32 Added Database Models

controllers/repositoryController.js, index.js, models/documentModel.js, models/folderModel.js, models/teamModel.js, routes/repositoryRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/28
-
=> KMNCORE-28 Added CreateRepository

controllers/teamController.js, controllers/userController.js, index.js, models/teamModel.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/29
-
=> KMNCORE-29 Added ApproveTeam

controllers/teamController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/30
-
=> KMNCORE-30 Added GetTeams and GetTeamById

controllers/teamController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/31
-
=> KMNCORE-31 Added UpdateTeam

controllers/folderController.js, index.js, models/documentModel.js, models/folderModel.js, models/teamModel.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/36
-
=> KMNCORE-36 Add CreateFolder

controllers/folderController.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/37
-
=> KMNCORE-37 Added GetAllChildrenById

controllers/folderController.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/38
-
=> KMNCORE-38 Added EditFolder

controllers/folderController.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/39
-
=> KMNCORE-39 Added DeleteFolder

controllers/documentController.js, index.js, routes/documentRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/40
-
=> KMNCORE-40 Added CreateDocument

controllers/documentController.js, routes/documentRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/41
-
=> KMNCORE-41 Added GetDocumentById

controllers/documentController.js, routes/documentRoute.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/43
-
=> KMNCORE-43 Added DeleteDocument

controllers/documentController.js, controllers/folderController.js, routes/documentRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/42
-
=> KMNCORE-42 Added UpdateDocument

controllers/userController.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/48
-
=> KMNCORE-48 Added SearchUser by Email

controllers/teamController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/34
-
=> KMNCORE-34 Added AddMember to Team

controllers/userController.js, models/userModel.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/60
-
=> KMNCORE-60 Added GetTeamByUserId 

models/teamModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/52
-
=> KMNCORE-62 Configured Team Status Enums (fix typo)

controllers/documentController.js, models/folderModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/64
- fixed `documentModel` import error
- fixed `folderSchema` nested schema
=> KMNCORE-64 Fixed Errors

controllers/documentController.js, controllers/teamController.js, index.js, models/folderModel.js, models/repositoryModel.js, models/teamModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/64
-
=> KMNCORE-64 Fixed Errors 

data/seeder.js, data/user.json, package.json
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/21
-
=> KMNCORE-21 Added User Data Seed

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/71
-
=> KMNCORE-71 Fixed getTeamsByUserId Controller

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/73
-
=> KMNCORE-73 Updated getTeamsByUserId

controllers/teamController.js, controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/75
-
=> KMNCORE-75 Updated `status` logic in updateTeam Controller

controllers/teamController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/77
-
=> KMNCORE-77 Added DeleteTeam

controllers/teamController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/79
-
=> KMNCORE-79 Updated GetTeams

controllers/teamController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/81
-
=> KMNCORE-81 Added Approve/Reject Team by Admin

controllers/teamController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/81
-
=> KMNCORE-81 Fixed Approve/Reject Team by Admin

controllers/userController.js, data/user.json
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/82
-
=> KMNCORE-82 Added Search Researcher by `fullName` and `email`

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/87
-
=> KMNCORE-87 Added Filter to getTeams

controllers/teamController.js, controllers/userController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/89
-
=> KMNCORE-89 Implemented Delete Team Members

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/91
-
=> KMNCORE-91 Updated getTeamsByUserId response

controllers/teamController.js, controllers/userController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/95
-
=> KMNCORE-95 Updated Routes to Prevent `over-fetching`

controllers/chatController.js, controllers/teamController.js, controllers/userController.js, index.js, package.json, routes/chatRoute.js, socket/index.js, yarn.lock
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/98
-
=> KMNCORE-98 Implement Realtime Message with `socket.io`

controllers/teamController.js, controllers/userController.js, models/teamModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/97
-
=> KMNCORE-97 Added `administrators` to `members` Field

controllers/adminController.js, controllers/teamController.js, controllers/userController.js, models/userModel.js, socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/94
-
=> KMNCORE-94 Fixed Issues

controllers/notificationController.js, index.js, models/messageModel.js, routes/notificationRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/104
-
=> KMNCORE-104 Added Notification and Unread Message in ReserachDiscussion

controllers/teamController.js, controllers/userController.js, utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/103
-
=> KMNCORE-103 Add `isGroupAdmin` aggregate in `members`

controllers/teamController.js, controllers/userController.js, models/userModel.js, utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/111
-
=> KMNCORE-111 Added `isAdmin` to and omit `administrators` from `populateTeam`

models/userModel.js, socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/116
-
=> KMNCORE-116 Allowed All `localhost` Origin from `socket`

config/db.js, controllers/teamController.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/119
- check wether `{ upsert: true }` on mongoDB update will help with this usecase
=> KMNCORE-119 Implemented Edit Member Role

controllers/teamController.js, controllers/userController.js, data/user.json, models/documentModel.js, models/folderModel.js, models/repositoryModel.js, models/teamModel.js, models/userModel.js, utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/93
-
=> KMNCORE-93 Added More Field to Database Schema 

controllers/folderController.js, controllers/teamController.js, models/documentModel.js, models/folderModel.js, models/repositoryModel.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/124
-
=> KMNCORE-124 Integrated Fetch Folders

controllers/folderController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/129
-
=> KMNCORE-129 Updated `updateFolder` Controller based on Data Specs

controllers/folderController.js, routes/folderRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/131
-
=> KMNCORE-131 Added `updateNote` Use Case

controllers/folderController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/133
-
=> KMNCORE-133 Added `deleteFolder` Use Case

controllers/documentController.js, controllers/teamController.js, models/documentModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/137
-
=> KMNCORE-137 Added Delete Document Use Case

controllers/documentController.js, controllers/teamController.js, models/documentModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/139
-
=> KMNCORE-139 Added Update Document Use Case

controllers/folderController.js, controllers/teamController.js, models/folderModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/141
- Added `parents` to `documentModel`
- Added parent aggregation in `getFolderById` controller
=> KMNCORE-141 Implemented Folder Structure

socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/118
-
=> KMNCORE-118 Fixed Chat Issue 🔥

models/messageModel.js, socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/143
-
=> KMNCORE-143 Added File Upload to Chat

controllers/documentController.js, controllers/folderController.js, controllers/teamController.js, data/seed.js, models/contributionModel.js, models/documentModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/150
-
=> KMNCORE-150 Add Contribution Field

controllers/documentController.js, controllers/folderController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/151
-
=> KMNCORE-151 Add Multiple Contributions to a Single Document

controllers/documentController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/152
-
=> KMNCORE-152 Add, Update and Delete Contributions to Existing Documents

utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/154
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/155
-
=> KMNCORE-154 Add Contribution Field

config/db.js, controllers/documentController.js, controllers/teamController.js, models/documentModel.js, models/teamModel.js, package-lock.json, routes/documentRoute.js, routes/teamRoute.js, utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/160
-
=> KMNCORE-160 Add Search By String Function

socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/167
-
=> KMNCORE-167 Updated Socket CORS Whitelist after Deployment

socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/167
-
=> KMNCORE-167 Update Socket CORS Whitelist after Deployment

models/messageModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/172
-
=> KMNCORE-172 Fixed Attachment Couldn't Be Downloaded

controllers/documentController.js, controllers/folderController.js, controllers/teamController.js, models/repositoryModel.js, routes/documentRoute.js, routes/folderRoute.js, routes/teamRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/174
-
=> KMNCORE-173 Add Route for Folder and Document without auth

controllers/teamController.js, models/teamModel.js, utils/queries.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/176
-
=> KMNCORE-176 Add Proposal Document

controllers/documentController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/179
-
=> KMNCORE-179 Updated Route for Searching Document By String

controllers/folderController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/181
-
=> KMNCORE-181 update getFolderById To Add Repository In The Result

controllers/documentController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/184
-
=> KMNCORE-184 Add `references` Field When Create and Update Document

controllers/documentController.js, controllers/folderController.js, models/documentModel.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/188
-
=> KMNCORE-188 Add Status/Version When Add and Edit Document

controllers/userController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/190
-
=> KMNCORE-190 Implement Not Accepted Account

controllers/folderController.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/192
-
=> KMNCORE-192 Add Reference to getFolderByDocumentId

controllers/userController.js, routes/userRoute.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/195
-
=> KMNCORE-195 Edit User Profile

socket/index.js
close https://github.com/Knowledge-Management-Capstone/knowledge-management-core/issues/171
-
=> KMNCORE-171 Fix Chat not Received in Disscussion Page
